---
title: "In-class template"
author: "Abby Malech"
format: pdf
---

# 1. Set up

## Packages

```{r}
#| label: packages

# general use and cleaning
library(tidyverse)
library(janitor)
library(here)
library(snakecase)

# wrap axis labels
library(scales)

# reading .xlsx files
library(readxl)

# visualize data using naniar
library(naniar)

# arrange plot using patchwork
library(patchwork)
```

## Data

```{r}
#| label: data

# taxonmic information
taxon_list <- read_csv(here("data", "taxon_list.csv"))

# aquatic invertebrates
aq_ins <- read_xlsx(
  here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
  sheet = "Aquatic Insects"
)

# site information
sites <- read_xlsx(
  here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
  sheet = "sites"
)

# water quality
water_quality <- read_xlsx(
  here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
  sheet = "Water Quality",
  na = c("", "n/a", "N/A", "over", "173+")
)

```

# 2. Cleaning

## Clean `sites` object

Goal: create a new object from sites that only includes NCOS sites

```{r}
#| label: NCOS-sites

# creating new object from sites
ncos_sites <- sites |> 
  # filter to only inclue NCOS quarterly sampling sites
  filter(sector == "NCOS" & sampling_frequency == "Quarterly")




```









