---
title: "Individual Assignment 5"
author: "Abby Malech"
format: pdf
date: "2026-05-11"
execute:
  message: false
  warning: false
---

# Packages
```{r}
#| label: load-packages

# general use and customization
library(tidyverse)
library(janitor)
library(here)
library(snakecase)

# wrapping axis labels
library(scales)

# reading in .xlsx files
library(readxl)

# visualizing missing data
library(naniar)

# arranging plots
library(patchwork)
```

```{r}
#| label: load-data

# taxonomic information
taxon_list <- read_csv(here("data", "taxon_list.csv")) 

# aquatic invertebrates
aq_ins <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                    sheet = "Aquatic Insects") 

# site information
sites <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                   sheet = "sites")

# water quality information
water_quality <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                           sheet = "Water Quality",
                           na = c("", "n/a", "N/A", "over", "173+"))
```

# Set Up

```{r}
#| label: in-class-code





```


# 1. Visualizing Differences across sites in major taxon abundance

## a. Plan your figure




## b. Wrangle your data





## c. Code your figure



## d. Create a multipanel figure



## e. Interpret your figure



# 2. Visualizing total abundance as a function of salinity


## a. Plan your figure



## b. Wrangle your data



## c. Code your figure


## d. Interpret your figure



